"""Write kaggle/job/kaggle_auction_llm.py: a self-contained Kaggle script (2x Tesla T4) that builds llama.cpp b11136
with CUDA, downloads Qwen3.5 GGUF files (bartowski Q4_K_M conversions) and runs code/llm_bidders.py for each model.
code/llm_bidders.py is embedded verbatim (base64), so the kernel needs no input dataset.
Push:   kaggle kernels push -p kaggle/job
Status: kaggle kernels status alexgorenkovv/auction-llm-bidders
Output: kaggle kernels output alexgorenkovv/auction-llm-bidders -p kaggle/out
"""
import base64
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = (HERE.parent / "code" / "llm_bidders.py").read_bytes()
MODELS = {
    "qwen4b": "https://huggingface.co/bartowski/Qwen_Qwen3.5-4B-GGUF/resolve/main/Qwen_Qwen3.5-4B-Q4_K_M.gguf",
    "qwen9b": "https://huggingface.co/bartowski/Qwen_Qwen3.5-9B-GGUF/resolve/main/Qwen_Qwen3.5-9B-Q4_K_M.gguf",
    "qwen27b": "https://huggingface.co/bartowski/Qwen_Qwen3.5-27B-GGUF/resolve/main/Qwen_Qwen3.5-27B-Q4_K_M.gguf",
}
REPEATS = 10

JOB = f'''"""Kaggle job (2x Tesla T4): LLM bidders for the timed proxy auction (paper 07). Generated by kaggle/make_job.py."""
import base64
import glob
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

W = Path("/kaggle/working")
TMP = Path("/tmp/job")
SRC, BUILD = TMP / "llama.cpp", TMP / "build"
TAG = "b11136"
MODELS = {json.dumps(MODELS, indent=4)}
REPEATS = {REPEATS}
LLM_BIDDERS = base64.b64decode("{base64.b64encode(SRC).decode()}")
T0 = time.time()


def log(msg):
    line = f"[{{time.time() - T0:7.0f}}s] {{msg}}"
    print(line, flush=True)
    with open(W / "job.log", "a") as f:
        f.write(line + "\\n")


def sh(cmd):
    log("$ " + " ".join(map(str, cmd)))
    subprocess.run(cmd, check=True)


def find_libcuda():
    for pat in ("/usr/lib/x86_64-linux-gnu/libcuda.so*", "/usr/local/cuda/lib64/stubs/libcuda.so",
                "/usr/local/nvidia/lib64/libcuda.so*"):
        hits = sorted(glob.glob(pat))
        if hits:
            return hits[0]
    return None


def build():
    sh(["git", "clone", "--depth", "1", "--branch", TAG, "https://github.com/ggml-org/llama.cpp", str(SRC)])
    base = ["cmake", "-S", str(SRC), "-B", str(BUILD), "-DGGML_CUDA=ON", "-DCMAKE_CUDA_ARCHITECTURES=75",
            "-DCMAKE_BUILD_TYPE=Release", "-DLLAMA_CURL=OFF", "-DLLAMA_OPENSSL=OFF"]
    lib = find_libcuda()
    try:
        sh(base + ([f"-DCUDA_cuda_driver_LIBRARY={{lib}}"] if lib else ["-DGGML_CUDA_NO_VMM=ON"]))
    except subprocess.CalledProcessError:
        shutil.rmtree(BUILD, ignore_errors=True)
        sh(base + ["-DGGML_CUDA_NO_VMM=ON"])
    sh(["cmake", "--build", str(BUILD), "--config", "Release", "-j", str(os.cpu_count()), "--target", "llama-server"])


def main():
    TMP.mkdir(parents=True, exist_ok=True)
    code = TMP / "code"
    code.mkdir(exist_ok=True)
    (code / "llm_bidders.py").write_bytes(LLM_BIDDERS)
    build()
    env = dict(os.environ, LLAMA_SERVER=str(BUILD / "bin" / "llama-server"), RESULTS_DIR=str(W / "results" / "llm"))
    for label, url in MODELS.items():
        path = TMP / Path(url).name
        sh(["wget", "-q", "-O", str(path), url])
        log(f"{{label}}: {{path.stat().st_size / 1e9:.1f}} GB")
        with open(W / f"{{label}}.log", "w") as lf:
            r = subprocess.run([sys.executable, str(code / "llm_bidders.py"), str(path), label, "99", str(REPEATS)],
                               env=env, stdout=lf, stderr=subprocess.STDOUT)
        log(f"{{label}} finished, exit code {{r.returncode}}")
        path.unlink()
    subprocess.run(["nvidia-smi"], stdout=open(W / "nvidia_smi.txt", "w"))
    log("done")


if __name__ == "__main__":
    main()
'''
(HERE / "job").mkdir(exist_ok=True)
(HERE / "job" / "kaggle_auction_llm.py").write_text(JOB, encoding="utf-8")
meta = {"id": "alexgorenkovv/auction-llm-bidders", "title": "auction-llm-bidders", "code_file": "kaggle_auction_llm.py",
        "language": "python", "kernel_type": "script", "is_private": True, "enable_gpu": True, "enable_internet": True,
        "dataset_sources": [], "competition_sources": [], "kernel_sources": []}
(HERE / "job" / "kernel-metadata.json").write_bytes(json.dumps(meta).encode("utf-8"))   # no BOM
print("written", HERE / "job")
