"""meta.json (Crossref / DataCite / IDEAS records fetched by fetch_all.py) -> ../refs.bib.
Every field comes from the fetched record; `verified` says where from. Manual fixes are listed in FIX."""
import json, re, html
d = json.load(open("meta.json"))
ex = json.load(open("landing.json")); s2 = json.load(open("s2.json"))
TODAY = "2026-09-25"
FIX = {"krishna2010auction": {"author": "Krishna, Vijay", "edition": "2", "publisher": "Academic Press (Elsevier)",
                              "note": "Crossref lists no author for this DOI; author from the ISBN 9780123745071 record"},
       "mizuta2000agent": {"year": "2000"},
       "bajari2003winner": {"author": "Bajari, Patrick and Horta\\c{c}su, Ali", "note": "Crossref lists the second author twice (Horta\u00e7su / Hortacsu)"}}
FIX.update({"milgrom1982theory": {"pages": "1089--1122", "note": "last page from IDEAS ecm/emetrp/v50y1982i5p1089-1122 (Crossref gives first page only)"},
  "bajari2003winner": {"author": "Bajari, Patrick and Horta\\c{c}su, Ali", "pages": "329--355",
                       "note": "Crossref lists the second author twice and gives the first page only; pages from IDEAS rje/randje/v34y2003i2p329-55"},
  "kagel2016auctions": {"title": "Auctions: A Survey of Experimental Research"}})
FIX.update({"wintr2008some": {"author": "Wintr, Ladislav", "title": "Some Evidence on Late Bidding in eBay Auctions"},
  "vickrey1961counterspeculation": {"title": "Counterspeculation, Auctions, and Competitive Sealed Tenders"},
  "bapna2004user": {"title": "User Heterogeneity and its Impact on Electronic Auction Market Design: An Empirical Exploration"},
  "roth2002last": {"author": "Roth, Alvin E. and Ockenfels, Axel"}, "ely2009sniping": {"author": "Ely, Jeffrey C. and Hossain, Tanjim"}})
DROP = {"houser2006hard"}  # Crossref record has no year; not needed

def clean(s): return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", "", s or ""))).strip()
def title_case_fix(t): return t.title().replace(" And ", " and ") if t.isupper() else t
def abstract_source(k, v):
    m = v["m"]
    if v["src"] == "crossref":
        if m.get("abstract"): return "Crossref abstract read"
        if (s2.get(k) or {}).get("abstract"): return "Semantic Scholar abstract read"
        for kk in (k, k + "_ssrn"):
            if ex.get(kk): return "abstract read (" + ("NBER/SSRN/IDEAS page" if "[" not in ex[kk][:2] else ex[kk][1:ex[kk].index("]")]) + ")"
        if k == "roth2002last": return "abstract of NBER w7729 working-paper version read"
        if k == "rasmusen2006strategic": return "abstract read (SSRN 267932 version, via Crossref)"
        return "metadata only (abstract not available)"
    if v["src"] == "datacite": return "arXiv abstract read (DataCite)"
    return "abstract read (IDEAS)"

out = [f"% refs.bib -- paper 07 (online auction design: proxy bidding, soft close, sniping; ABM + LLM bidders).\n"
       f"% Generated by lit/_work/make_bib.py from records fetched on {TODAY} (Crossref api.crossref.org/works/<DOI>,\n"
       f"% DataCite api.datacite.org for arXiv DOIs, IDEAS/RePEc page for the one article Crossref lacks).\n"
       f"% Field `verified` = where the record and the abstract came from. keywords = tags (see notes.md).\n"]
for k, v in d.items():
    if k in DROP: continue
    m, f = v["m"], {}
    if v["src"] == "crossref":
        typ = {"journal-article": "article", "book-chapter": "incollection", "proceedings-article": "inproceedings",
               "monograph": "book", "edited-book": "book", "report": "techreport"}[m["type"]]
        f["author"] = " and ".join(f"{a['family'].title() if a['family'].isupper() else a['family']}, {a.get('given','')}".strip(", ")
                                   for a in m.get("author", []) if "family" in a)
        f["title"] = title_case_fix(clean(m["title"][0]))
        if m["type"] == "book-chapter" and f["title"].startswith(("Chapter 12 ", "9. ")):
            f["title"] = re.sub(r"^(Chapter 12 |9\. )", "", f["title"])
        f["year"] = str(m["issued"]["date-parts"][0][0]) if m["issued"]["date-parts"][0][0] else ""
        ct = [clean(c) for c in m.get("container-title", [])]
        if typ == "article":
            f["journal"] = ct[0] if ct else ""
            f["volume"], f["number"], f["pages"] = m.get("volume", ""), m.get("issue", ""), m.get("page", "").replace("-", "--")
        elif typ in ("incollection", "inproceedings"):
            f["booktitle"] = ct[-1] if ct else ""
            if ct and len(ct) > 1: f["series"] = ct[0]
            f["pages"] = m.get("page", "").replace("-", "--")
            f["publisher"] = m.get("publisher", "")
            if m.get("editor"): f["editor"] = " and ".join(f"{e['family']}, {e['given']}" for e in m["editor"])
        elif typ == "book":
            f["publisher"] = m.get("publisher", "")
        else:
            f["institution"] = m.get("publisher", ""); f["number"] = "Working Paper " + m["DOI"].split("/w")[-1]
        f["doi"] = m["DOI"].lower() if m["DOI"].startswith("10.3386") else m["DOI"]
        f["verified"] = f"Crossref DOI lookup {TODAY}; {abstract_source(k, v)}"
    elif v["src"] == "datacite":
        typ = "misc"
        f["author"] = " and ".join(f"{c['familyName']}, {c.get('givenName','')}" for c in m["creators"] if c.get("familyName"))
        if not f["author"]:
            f["author"] = "Yang, An and others"
        f["title"] = m["titles"][0]["title"]; f["year"] = str(m["publicationYear"])
        f["eprint"] = m["doi"].split("arxiv.")[-1]; f["archiveprefix"] = "arXiv"; f["doi"] = m["doi"]
        f["verified"] = f"DataCite/arXiv lookup {TODAY}; {abstract_source(k, v)}"
    else:
        typ = "article"
        f["author"] = " and ".join(f"{n.split()[-1]}, {' '.join(n.split()[:-1])}" for n in m["authors"].split("; "))
        f["title"], f["journal"], f["year"] = m["title"], m["journal_title"], m["year"]
        f["volume"], f["number"], f["pages"] = m["volume"], m["issue"], f"{m['firstpage']}--{m['lastpage']}"
        f["url"] = v["url"]
        f["verified"] = f"IDEAS/RePEc record {TODAY} (not in Crossref); {abstract_source(k, v)}"
    f.update(FIX.get(k, {}))
    f["keywords"] = v["tags"]
    body = ",\n".join(f"  {a:<9}= {{{b}}}" for a, b in f.items() if b)
    out.append(f"@{typ}{{{k},\n{body}\n}}\n")
open("../refs.bib", "w").write("\n".join(out))
print(len(out) - 1, "entries")
